# texts.toml
# Alle anpassbaren Texte der Anwendung
# Kann vom Admin ohne Python-Kenntnisse bearbeitet werden.

# Kontaktperson, die auf den Seiten angezeigt wird
[kontaktperson]
nachname      = "Koch"
vorname       = "Kay"
mail          = "koch@tssbit.de"
komplett      = "OStR Kay Koch (koch@tssbit.de)" 

# Name der Schule, die auf den Seiten angezeigt wird. Das Logo kann im Ordner static geändert werden
# Vollständige Domain, auf die der Dienst läuft
# Loginname der Lehrkräfte. Passwort wird in der DB geändert
[schule]
name           = "Theobald-Simon-Schule"
url            = "https://sprechtag.tss-bitburg.de"
lehrkraftlogin = "tssbit"

[sprechtag]
sprechtag_wartezeit = 17
sprechtag_titel = "Ausbilder- und Elternsprechtag: "

